<?php

namespace EasyCloud\EasyCloudBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * licencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicencesRepository extends EntityRepository
{
}
